name: Build Output Deploy_Test

on:
  push:
    branches:
      - feature/V11_Full

  workflow_dispatch:

concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
